# Workflow name
name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
               
      - uses: actions/checkout@v3
      - name: Install Python Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run linter on source files
        run: |
          pylint --verbose --rcfile=pylintrc user/*
          pylint --verbose --rcfile=pylintrc publish/*
          pylint --verbose --rcfile=pylintrc request/*
          pylint --verbose --rcfile=pylintrc search/*

      - name: Run django tests
        run: |
          echo "database:" > config.yml
          echo "  endpoint: packtravel.cyumok3.mongodb.net/?retryWrites=true&w=majority" >> config.yml
          echo "  username: ${{secrets.DB_USERNAME}}" >> config.yml
          echo "  password: ${{secrets.DB_PASSWORD}}" >> config.yml
          coverage run ./manage.py test          
          coverage xml --data-file .coverage -o coverage.xml
          coverage report --data-file .coverage -m
          
      - name : Send test coverage report
        run: |
          pip install codacy-coverage
          export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}
          export CODACY_API_TOKEN=${{ secrets.CODACY_API_TOKEN }}
          export CODACY_USERNAME=VSangarya
          export CODAY_PROJECT_NAME=PackTravel
          python-codacy-coverage -r coverage.xml
