name: sphinx-autogenerator

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build documentation and commit
              run: |
                  git pull origin adding_docs
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  sudo apt-get install python3-sphinx                
                  sphinx-apidoc -f -o docs/source PackTravel
                  sphinx-apidoc -f -o docs/source publish
                  sphinx-apidoc -f -o docs/source request
                  sphinx-apidoc -f -o docs/source search
                  sphinx-apidoc -f -o docs/source user
                  cd docs/
                  make html
                  cd ..
                  git config --global user.name "qureshi-ali"
                  git config --global user.email "qureshi.ali@outlook.com"
                  git add .
                  git commit -m "updating docs" -a || true
                  git push
        # ===============================
